version: "3.9"
services:
  telco-prediction:
    build: .
    container_name: telco-prediction
    image: telco-prediction
    env_file: .env
    command: python main.py
    ports:
      - 5000:5000
    volumes:
      - ./app:/app
      - ./model:/model
    networks:
      - telco-prediction

networks:
  telco-prediction:
    name: telco-prediction